createSearchInputSelect
peaksoft-school/GiftList-js13 pull request #8
Opened 2024-07-07 12:15 UTC by Syrgabeka

2024-07-10 14:27 UTC, AziatAbd requested changes

2024-07-10 14:27 UTC, AziatAbd commented on src/app/App.tsx
> +
напишите все эти функции внутри компонента SearchInput.tsx и пусть эта компонента принимает в себя props value который будет возвращать объект с данными из селектов и инпута

2024-07-10 14:27 UTC, AziatAbd commented
дайте width: 100% для searchinput

2024-07-12 12:05 UTC, Syrgabeka commented on src/app/App.tsx
> +
StyledInput fullWidth берип койгом

2024-07-13 12:34 UTC, merged